version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/front-end-foodapp
    ports:
      - 3000:3000
    image: app:react
    container_name: react-container
    command: npm start